# robust training options
framework: mbrdl
w_src: 0.1
w_xi: 0

# classifier options
arch: resnet18small
lr_scheduler_type: cosine
image_size: 32
batch_size: 256
max_epochs: 200

# logger options
ckpt_freq: 200
print_freq: 50

# mbrdl options
mbrdl_model_config: 'mbrdl/core/models/munit/munit.yaml'