# robust training options
framework: simclr
w_src: 1
w_xi: 0

# classifier options
arch: resnet18latent
lr_scheduler_type: cosine
image_size: 32
batch_size: 256
max_epochs: 200

# logger options
ckpt_freq: 200
print_freq: 50
